### ISSUE TITLE
Change HMD whitelist to HMD blacklist

### ISSUE THREAD

**Issue by simlrh** [simlrh/OSVR-OpenHMD#3]
The latest release should allow HMDs with any name to be recognised

@Bungpiece, are you able to test whether this works with your DK2? (Sorry for the wait)

**Comment by Bungpiece** [comment]
No worries man. I'll try and have a bash with it this weekend. Thanks for the update.

**Comment by Bungpiece** [comment]
Sorry for the delay. I've had on and off issues with my PC and OSVR to be sure where my issues were occurring. The issue was on my end I only have a DK2 clone the Deepoon E2. Which is only just [supported](http://www.vronlinux.com/articles/deepoon-e2-mojolicious-excel-oh-my.32) and not integrated into the main branch of the openHMD.
Sorry for the confusion.
